### ISSUE TITLE
Rename `config.yml` to default or sample and do not include debug.log to git repo

### ISSUE THREAD

**Issue by poppinlp** [RiceQuant-FE/fortal#1]
There may be two ways to resolve real info in config file:

- Use a sample file to show a example and read from another config file
- Use a default file to describe default config and a custom file to extend that

They are all accepted. You could choose one.

The `npm-debug.log` should not be included into git repo. You may update your `.gitignore` file like [this one](https://github.com/poppinlp/eslint-config-handsome/blob/master/.gitignore).

**Comment by lithium2013** [comment]
Fixed [0a7c2bb8264e746e31aeaa284b0ab940f100983c](https://github.com/RiceQuant-FE/fortal/commit/0a7c2bb8264e746e31aeaa284b0ab940f100983c)
